---
downloads: ~/.ansible-downloads/

# Download and install dotfiles
  configure_dotfiles: true
  
  dotfiles_repo: https://github.com/ryanmroth/dotfiles.git
  dotfiles_repo_accept_hostkey: true
  dotfiles_repo_local_destination: ~/Development/dotfiles
  dotfiles_files:
    - .asdf
    - .curlrc
    - .editorconfig
    - .ffufrc
    - .gemrc
    - .gitattributes
    - .hushlogin
    - .macos
    - .wgetrc
    - .zshrc

# Install Terminal profile
  configure_terminal: true

# Deploy important Mac defaults
  configure_macos: true
  macos_config_script: "~/.macos --no-restart"

# Add and remove items from the Dock
  configure_dock: true
  dockitems_remove: []
    - Launchpad
    - Safari
    - Mail
    - Contacts
    - Calendar
    - Notes
    - Reminders
    - Maps
    - Messages
    - Facetime
    - TV
    - Photos
    - Music
    - Podcasts
    - Siri
    - Numbers
    - Keynote
    - News
    - 'App Store'
    - 'System Settings'
  dockitems_persist: []
    - name: "Firefox"
      path: "/Applications/Firefox.app/"
      pos: 2
    - name: "Visual Studio Code"
      path: "/Applications/Visual Studio Code.app/"
      pos: 3
    - name: "Microsoft Teams"
      path: "/Applications/Microsoft Teams.app/"
      pos: 4
    - name: "iTerm"
      path: "/Applications/iTerm.app/"
      pos: 5
    - name: "System Settings"
      path: "/Applications/System Settings.app/"
      pos: 7

# Brew package installation
  homebrew_installed_packages:
    - apktool
    - asdf
    - autoconf
    - azure-cli
    - binwalk
    - dalfox
    - dex2jar
    - dnstwist
    - dnsx
    - exiftool
    - exploitdb
    - ffuf
    - gh
    - git
    - gobuster
    - gpg
    - hashcat
    - httpx
    - hydra
    - ike-scan
    - jd-gui
    - john-jumbo
    - jython
    - karabiner-elements
    - mas
    - masscan
    - name-that-hash
    - neo4j
    - netcat
    - ngrok
    - nikto
    - nmap
    - nuclei
    - openssl
    - pinentry
    - pinentry-mac
    - proxychains-ng
    - radare2
    - recon-ng
    - rustscan
    - search-that-hash
    - shodan
    - sslscan
    - subfinder
    - sqlmap
    - sqlite
    - telnet
    - temurin
    - terraform
    - virustotal-cli
    - volatility
    - wget
    - yara
    - ykman
    - zsh-autosuggestions
    - zsh-syntax-highlighting

  homebrew_taps:
    - homebrew/core
    - homebrew/cask
    - homebrew/cask-fonts

  homebrew_cask_appdir: /Applications
  homebrew_cask_apps:
    - blockblock
    - bloodhound
    - cyberduck
    - discord
    - docker
    - firefox
    - font-hack
    - ghidra
    - github
    - google-chrome
    - imhex
    - iterm2
    - knockknock
    - lulu
    - microsoft-office
    - microsoft-remote-desktop
    - microsoft-teams
    - monitorcontrol
    - owasp-zap
    - postman
    - powershell
    - sequel-ace
    - tor-browser
    - visual-studio-code
    - vmware-fusion
    - wireshark
    - zoom

  # See `geerlingguy.mas` role documentation for usage instructions.
    mas_installed_apps:
      - { id: 937984704, name: "Amphetamine" }
      - { id: 441258766, name: "Magnet" }

# Configure Sublime Text preferences and plugins
  configure_sublime: true
  sublime_base_path: "~/Library/Application Support/Sublime Text 3"
  sublime_config_path: "Packages/User"
  sublime_package_control:
    - "Alignment"
    - "BracketHighlighter"
    - "Color Highlight"
    - "DocBlockr"
    - "MarkdownEditing"
    - "MarkdownPreview"
    - "Package Control"
    - "FileDiffs"
    - "Pretty JSON"
    - "SublimeLinter"
    - "WordCount"
    - "PlainNotes"

# Install Oh My Zsh and add custom files
  configure_ohmyzsh: true

# Install asdf plugins and setup defaults
  configure_asdf: true

# Install and setup pipx
  configure_pipx: true

# Copy custom Karabiner Elements configurations
  configure_karabiner: true

# Copy custom Wireshark profiles
  configure_wireshark: true

# Clone Github tool repos
  clone_repos: true
  repos:
    - repo: https://github.com/ryanmroth/git-dumper.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/Git-Dumper
      branch: master
    - repo: https://github.com/dafthack/GraphRunner.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/GraphRunner
      branch: main
    - repo: https://github.com/danielmiessler/SecLists.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/SecLists
      branch: master
    - repo: https://github.com/iamj0ker/bypass-403.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/Bypass-403
      branch: main
    - repo: https://github.com/Dionach/CMSmap
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/CMSmap
      branch: master
    - repo: https://github.com/dafthack/MFASweep.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/MFASweep
      branch: master
    - repo: https://github.com/WesSec/VelociDeploy-o-Matic.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/VelociDeploy
      branch: novpn
    - repo: https://github.com/initstring/cloud_enum.git
      dest: /Users/{{ lookup('env', 'USER') }}/Tools/Cloud_Enum
