---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    - import_tasks: tasks/ohmyzsh.yml
      when: configure_ohmyzsh
      tags: ["ohmyzsh"]
    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]
    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ["sublime-text"]
    - import_tasks: tasks/asdf.yml
      when: configure_asdf
      tags: ["asdf"]
    - import_tasks: tasks/karabiner.yml
      when: configure_karabiner
      tags: ["karabiner"]
    - import_tasks: tasks/macos.yml
      when: configure_macos
      tags: ["macos"]
