---
- name: Install Oh My ZSH.
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

- name: Copy custom Oh My ZSH files.
  copy:
    src: "{{ item }}"
    dest: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/"
  with_fileglob: "files/ohmyzsh/*"
